language: rust

matrix:
  include:
    - env: TARGET=armebv7r-none-eabihf
      rust: nightly

    - env: TARGET=armebv7r-none-eabi
      rust: nightly

before_install: set -e

install:
  - bash ci/install.sh

script:
  - bash ci/script.sh

addons:
  apt:
    sources:
    - sourceline: 'ppa:team-gcc-arm-embedded/ppa'
    packages:
    - gcc-arm-embedded

after_script: set +e

cache: cargo

before_cache:
  - chmod -R a+r $HOME/.cargo;

notifications:
  email:
    on_success: never
